### PR TITLE
Added date for each notes.

### PR DESCRIPTION
**Pull request by Amisha328**

### CODE REVIEW

**Comment by Amisha328** [comment]
Hey, @shvmsaini 
Please check PR #5 and let me know if any further changes are required.

**Comment by shvmsaini** [comment]
Seems like you didn't compile the app before making this PR.
1. Classes haven't been added.
2. list_item orientation isn't changed. 
3. If you copy/paste the code, make sure it is properly formatted and is up-to-date including comments.

**Comment by Amisha328** [comment]
Hey, @shvmsaini,
I apologize for the inconvenience caused.
Actually, the cloned repo is showing too many additional bugs with Gradle which I tried to resolve but could not succeed. So, I created a local project and implemented the desired feature and the application was working fine which I pasted in the original repo.

But, it seems I made mistake in pasting the code from my local repo to the original repo.  

[Feature implemenation](https://drive.google.com/file/d/1l8rhaTeJyidxp6a-bAwuFGrUBMDQwABZ/view?usp=sharing)

**Comment by Amisha328** [comment]
I will fix this ASAP.

**Pull request closed without merging**
